# Bases and transformations
The following tasks are designed to provide a refresher on bases and transformations between them.

<article class="message">
    <div class="message-body">
        <strong>List of individual tasks</strong>
        <ul style="list-style: none;">
            <li>
            <a href="#basis">Task 1: Identifying Basis Vectors</a>
            </li>
            <li>
            <a href="#basis_combined">Task 2: Basis Transformation and Change of Coord…</a>
            </li>
            <li>
            <a href="#basis4">Task 3: Applying a Linear Transformation in Diff…</a>
            </li>
            <li>
            <a href="#basis5">Task 4: Basis and Dimensionality Check</a>
            </li>
        </ul>
    </div>
</article>


---
**Task 1 (easy): Identifying Basis Vectors♾️**
Given the following bases vectors for $\mathbb{R}^2$:

$$
\begin{array}{l}
1. \left\{ \begin{bmatrix} 1 \\ 0 \end{bmatrix}, \begin{bmatrix} 0 \\ 1 \end{bmatrix} \right\} \\[12pt]
2. \left\{ \begin{bmatrix} 2 \\ 3 \end{bmatrix}, \begin{bmatrix} -1 \\ 2 \end{bmatrix} \right\} \\[12pt]
3. \left\{ \begin{bmatrix} 1 \\ 1 \end{bmatrix}, \begin{bmatrix} 2 \\ 2 \end{bmatrix} \right\} \\
\end{array}
$$
1. Which of these sets forms a basis for $\mathbb{R}^2 $? Justify your answer by checking linear independence and spanning the vector space.


---

In [0]:
# Write solutions here
# 1 is a basis for R^2 as the matrix with the vectors as columns has
# # a non-zero determinant (linearly INdependent):
A1 = [[1, 0],
    [0, 1]]
# 2 is a basis for R^2 as the matrix with the vectors as columns has
# # a non-zero determinant (linearly INdependent):
B1 = [[2, -1],
    [3, 2]]
B2 = [[7, 0], # R2 += 2 * R1 && R1 <=> R2
    [2, -1]]
B3 = [[1, 0], # R1 *= 1/7 && R2 *= -1
    [-2, 1]]
B4 = [[1, 0], # R2 += 2 * R1
    [0, 1]]
# 3 is NOT a basis for R^2 as the matrix with the vectors as columns has
# # a zero determinant (linearly dependent):
C1 = [[1, 2],
    [1, 2]]
C2 = [[1, 2], # R2 -= R1
    [0, 0]] # oops, 0-row mean bad luck :'(


---
**Task 2 (hard): Basis Transformation and Change of Coordinates♾️**
Consider three bases in  $\mathbb{R}^2$:
1. The standard basis  
$$E = \left\{ \begin{bmatrix} 1 \\ 0 \end{bmatrix}, \begin{bmatrix} 0 \\ 1 \end{bmatrix} \right\}$$
 
2. The basis  
$$B   = \left\{ \begin{bmatrix} 1 \\ 2 \end{bmatrix}, \begin{bmatrix} 2 \\ -1 \end{bmatrix} \right\}$$
 
3. The basis  
$$C   = \left\{ \begin{bmatrix} 2 \\ 1 \end{bmatrix}, \begin{bmatrix} 1 \\ 3 \end{bmatrix} \right\}$$
 

Given two vectors in the standard basis:

$$
\text{v} = \begin{bmatrix} 3 \\ 1 \end{bmatrix}, 
\text{w} = \begin{bmatrix} 7 \\ 6 \end{bmatrix} 
$$
1. Draw the basis vectors for  $E$,  $B$ , and  $C$ and the vectors $\text{v}$ and $\text{w}$  on a piece of paper.

2. Express $\text{v}$ and $\text{w}$  in the basis  $B$. 

3. Express $\text{v}$  and $\text{w}$  in the basis $C$.

4. Find the change of basis matrix  $T_E^B$ that given a vector expressed in the basis  E  maps it to the basis B. 

5. Find the change of basis matrix  $T_E^C$ that given a vector expressed in the basis  E  maps it to the basis C.

6. Use the change of basis matrices to transform  $\text{v}$ and $\text{w}$ from standard basis to the basis $B$ and $C$ respectively. Verify that the resulting coordinates match your results from the previous steps.



---

In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Define the bases
E = np.array([[1, 0], [0, 1]])  # Standard basis
B = np.array([[1, 2], [2, -1]])  # Basis B
C = np.array([[2, 1], [1, 3]])  # Basis C

# Given vectors in standard basis
v = np.array([3, 1])
w = np.array([7, 6])

print("="*60)
print("TASK 2: Basis Transformation and Change of Coordinates")
print("="*60)

# Question 2: Express v and w in basis B
# We need to solve: v = a*b1 + b*b2, where b1, b2 are basis vectors of B
# This is: [v] = B * [a, b]^T, so [a, b]^T = B^(-1) * [v]

B_inv = np.linalg.inv(B)
v_in_B = B_inv @ v
w_in_B = B_inv @ w

print("\n2. Expressing v and w in basis B:")
print(f"   v in basis B: {v_in_B}")
print(f"   w in basis B: {w_in_B}")
print(f"   Verification: B @ v_in_B = {B @ v_in_B} (should equal v = {v})")

# Question 3: Express v and w in basis C
C_inv = np.linalg.inv(C)
v_in_C = C_inv @ v
w_in_C = C_inv @ w

print("\n3. Expressing v and w in basis C:")
print(f"   v in basis C: {v_in_C}")
print(f"   w in basis C: {w_in_C}")
print(f"   Verification: C @ v_in_C = {C @ v_in_C} (should equal v = {v})")

# Question 4: Change of basis matrix T_E^B
# T_E^B transforms coordinates from E to B
# Since E is standard basis, T_E^B = B^(-1)
T_E_to_B = np.linalg.inv(B)
print("\n4. Change of basis matrix T_E^B (from E to B):")
print(T_E_to_B)
print("   Explanation: T_E^B = B^(-1) because B is the matrix with basis B vectors as columns")

# Question 5: Change of basis matrix T_E^C
T_E_to_C = np.linalg.inv(C)
print("\n5. Change of basis matrix T_E^C (from E to C):")
print(T_E_to_C)
print("   Explanation: T_E^C = C^(-1) because C is the matrix with basis C vectors as columns")

# Question 6: Verify using change of basis matrices
v_B_using_matrix = T_E_to_B @ v
w_B_using_matrix = T_E_to_B @ w
v_C_using_matrix = T_E_to_C @ v
w_C_using_matrix = T_E_to_C @ w

print("\n6. Verification using change of basis matrices:")
print(f"   v in basis B (using T_E^B): {v_B_using_matrix}")
print(f"   v in basis B (from step 2): {v_in_B}")
print(f"   Match: {np.allclose(v_B_using_matrix, v_in_B)}")

print(f"\n   w in basis B (using T_E^B): {w_B_using_matrix}")
print(f"   w in basis B (from step 2): {w_in_B}")
print(f"   Match: {np.allclose(w_B_using_matrix, w_in_B)}")

print(f"\n   v in basis C (using T_E^C): {v_C_using_matrix}")
print(f"   v in basis C (from step 3): {v_in_C}")
print(f"   Match: {np.allclose(v_C_using_matrix, v_in_C)}")

print(f"\n   w in basis C (using T_E^C): {w_C_using_matrix}")
print(f"   w in basis C (from step 3): {w_in_C}")
print(f"   Match: {np.allclose(w_C_using_matrix, w_in_C)}")

# Visualization for question 1 (optional - can be done on paper)
print("\n1. For visualization, plot the basis vectors and given vectors:")
print("   (This should be done on paper as requested)")
print("   - Standard basis E: e1 = [1,0], e2 = [0,1]")
print("   - Basis B: b1 = [1,2], b2 = [2,-1]")
print("   - Basis C: c1 = [2,1], c2 = [1,3]")
print("   - Vectors: v = [3,1], w = [7,6]")

TASK 2: Basis Transformation and Change of Coordinates

2. Expressing v and w in basis B:
   v in basis B: [1. 1.]
   w in basis B: [3.8 1.6]
   Verification: B @ v_in_B = [3. 1.] (should equal v = [3 1])

3. Expressing v and w in basis C:
   v in basis C: [ 1.6 -0.2]
   w in basis C: [3. 1.]
   Verification: C @ v_in_C = [3. 1.] (should equal v = [3 1])

4. Change of basis matrix T_E^B (from E to B):
[[ 0.2  0.4]
 [ 0.4 -0.2]]
   Explanation: T_E^B = B^(-1) because B is the matrix with basis B vectors as columns

5. Change of basis matrix T_E^C (from E to C):
[[ 0.6 -0.2]
 [-0.2  0.4]]
   Explanation: T_E^C = C^(-1) because C is the matrix with basis C vectors as columns

6. Verification using change of basis matrices:
   v in basis B (using T_E^B): [1. 1.]
   v in basis B (from step 2): [1. 1.]
   Match: True

   w in basis B (using T_E^B): [3.8 1.6]
   w in basis B (from step 2): [3.8 1.6]
   Match: True

   v in basis C (using T_E^C): [ 1.6 -0.2]
   v in basis C (from step 3): [ 1.


---
**Task 3 (easy): Applying a Linear Transformation in Different Bases♾️**
Let $ T: \mathbb{R}^2 \to \mathbb{R}^2 $ be a linear transformation represented by the matrix:

$$
A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}
$$

in the standard basis. Let 

$$
B = \left\{ \begin{bmatrix} 1 \\ 1 \end{bmatrix}, \begin{bmatrix} -1 \\ 2 \end{bmatrix} \right\}
$$
 
be a new basis.
1. Calculate the matrix that represents $ T $ with respect to the basis $ B $. Use the change of basis matrices to show your work.


---

In [2]:
print("\n" + "="*60)
print("TASK 3: Applying a Linear Transformation in Different Bases")
print("="*60)

# Transformation matrix in standard basis
A = np.array([[1, 2],
              [3, 4]])

# New basis B
B_basis = np.array([[1, -1],
                    [1,  2]])

print("\nGiven:")
print(f"Transformation matrix A (in standard basis E):")
print(A)
print(f"\nNew basis B:")
print(B_basis)

# To find the matrix representation of T in basis B:
# 1. Find change of basis matrix from B to E: P = B (columns are basis vectors)
# 2. Find change of basis matrix from E to B: P^(-1) = B^(-1)
# 3. The transformation matrix in basis B is: A_B = P^(-1) * A * P

P = B_basis  # Change of basis from B to E
P_inv = np.linalg.inv(P)  # Change of basis from E to B

# Transformation matrix in basis B
A_B = P_inv @ A @ P

print("\nSolution:")
print("Step 1: Change of basis matrix from B to E: P = B")
print(P)
print("\nStep 2: Change of basis matrix from E to B: P^(-1) = B^(-1)")
print(P_inv)
print("\nStep 3: Transformation matrix in basis B: A_B = P^(-1) * A * P")
print("A_B =")
print(A_B)

print("\nVerification:")
print("If we transform a vector [x]_B in basis B:")
print("1. Convert to standard basis: P * [x]_B = [x]_E")
print("2. Apply transformation: A * [x]_E = A * P * [x]_B")
print("3. Convert back to basis B: P^(-1) * A * P * [x]_B = A_B * [x]_B")
print("\nSo A_B = P^(-1) * A * P correctly represents T in basis B")


TASK 3: Applying a Linear Transformation in Different Bases

Given:
Transformation matrix A (in standard basis E):
[[1 2]
 [3 4]]

New basis B:
[[ 1 -1]
 [ 1  2]]

Solution:
Step 1: Change of basis matrix from B to E: P = B
[[ 1 -1]
 [ 1  2]]

Step 2: Change of basis matrix from E to B: P^(-1) = B^(-1)
[[ 0.66666667  0.33333333]
 [-0.33333333  0.33333333]]

Step 3: Transformation matrix in basis B: A_B = P^(-1) * A * P
A_B =
[[4.33333333 3.66666667]
 [1.33333333 0.66666667]]

Verification:
If we transform a vector [x]_B in basis B:
1. Convert to standard basis: P * [x]_B = [x]_E
2. Apply transformation: A * [x]_E = A * P * [x]_B
3. Convert back to basis B: P^(-1) * A * P * [x]_B = A_B * [x]_B

So A_B = P^(-1) * A * P correctly represents T in basis B



---
**Task 4 (easy): Basis and Dimensionality Check♾️**
Suppose $ \mathbb{R}^3 $ has a basis given by 

$$
B = \left\{ \begin{bmatrix} 1 \\ 0 \\ 1 \end{bmatrix}, \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}, \begin{bmatrix} 1 \\ -1 \\ 0 \end{bmatrix} \right\}.
$$

1. Verify that $ B $ is a basis by showing it spans $ \mathbb{R}^3 $ and is linearly independent.
2. If a fourth vector $ \begin{bmatrix} 2 \\ -1 \\ 3 \end{bmatrix} $ is added to $ B $, does it still form a basis for $ \mathbb{R}^3 $? Explain your reasoning in terms of dimension.


---

In [4]:
print("\n" + "="*60)
print("TASK 4: Basis and Dimensionality Check")
print("="*60)

# Given basis B
B = np.array([[1, 0, 1],
              [0, 1, 1],
              [1, -1, 0]]).T  # Transpose to get vectors as columns

print("\nGiven basis B (vectors as columns):")
print(B)

# Question 1: Verify B is a basis
print("\n1. Verifying B is a basis for R^3:")
print("   a) Check linear independence (det(B) ≠ 0):")
det_B = np.linalg.det(B)
print(f"      det(B) = {det_B}")
if abs(det_B) > 1e-10:
    print("      ✓ Non-zero determinant → vectors are linearly independent")
else:
    print("      ✗ Zero determinant → vectors are linearly dependent")

print("\n   b) Check spanning R^3:")
# For R^3, we need 3 linearly independent vectors
# If det ≠ 0, the vectors span R^3
rank_B = np.linalg.matrix_rank(B)
print(f"      rank(B) = {rank_B}")
if rank_B == 3:
    print("      ✓ Rank is 3 → vectors span R^3")
    print("      Since we have 3 linearly independent vectors in R^3, they form a basis")
else:
    print("      ✗ Rank is less than 3 → vectors do not span R^3")

print(f"\n   Conclusion: B {'IS' if abs(det_B) > 1e-10 and rank_B == 3 else 'IS NOT'} a basis for R^3")

# Question 2: Adding a fourth vector
fourth_vector = np.array([2, -1, 3])
B_extended = np.column_stack([B, fourth_vector])

print("\n2. Adding fourth vector [2, -1, 3]^T to B:")
print(f"   Extended set: {B_extended.shape[1]} vectors in R^3")

print("\n   Checking linear independence of extended set:")
rank_extended = np.linalg.matrix_rank(B_extended)
print(f"   rank(extended set) = {rank_extended}")

if rank_extended > 3:
    print("   → The fourth vector is linearly dependent on the original 3 vectors")
    print("   → It can be expressed as a linear combination of the basis vectors")
    
    # Find the linear combination
    coeffs = np.linalg.solve(B, fourth_vector)
    print(f"\n   The fourth vector = {coeffs[0]:.2f}*b1 + {coeffs[1]:.2f}*b2 + {coeffs[2]:.2f}*b3")
    print(f"   Verification: B @ coeffs = {B @ coeffs} (should equal {fourth_vector})")
    
print("\n   Reasoning in terms of dimension:")
print("   - R^3 has dimension 3")
print("   - A basis for R^3 must have exactly 3 linearly independent vectors")
print("   - If we add a 4th vector, we have 4 vectors in a 3-dimensional space")
print("   - By the dimension theorem, at least one vector must be linearly dependent")
print("   - Therefore, the extended set CANNOT form a basis for R^3")
print("   - The maximum number of linearly independent vectors in R^3 is 3")



TASK 4: Basis and Dimensionality Check

Given basis B (vectors as columns):
[[ 1  0  1]
 [ 0  1 -1]
 [ 1  1  0]]

1. Verifying B is a basis for R^3:
   a) Check linear independence (det(B) ≠ 0):
      det(B) = 0.0
      ✗ Zero determinant → vectors are linearly dependent

   b) Check spanning R^3:
      rank(B) = 2
      ✗ Rank is less than 3 → vectors do not span R^3

   Conclusion: B IS NOT a basis for R^3

2. Adding fourth vector [2, -1, 3]^T to B:
   Extended set: 4 vectors in R^3

   Checking linear independence of extended set:
   rank(extended set) = 3

   Reasoning in terms of dimension:
   - R^3 has dimension 3
   - A basis for R^3 must have exactly 3 linearly independent vectors
   - If we add a 4th vector, we have 4 vectors in a 3-dimensional space
   - By the dimension theorem, at least one vector must be linearly dependent
   - Therefore, the extended set CANNOT form a basis for R^3
   - The maximum number of linearly independent vectors in R^3 is 3
