# Linear Algebra

**Overview**
This exercise is a continuation of week 3 exercise Basic Linear Algebra in Python
. It introduces how to solve linear systems of equations using linear algebra. The goal is to get familiarized with the concepts of linear algebra and how to use them in Numpy.


<article class="message">
    <div class="message-body">
        <strong>List of individual tasks</strong>
        <ul style="list-style: none;">
            <li>
            <a href="#inverses">Task 1: Inverses</a>
            </li>
            <li>
            <a href="#inverse_prop">Task 2: Inverse properties</a>
            </li>
            <li>
            <a href="#determinant">Task 3: The determinant</a>
            </li>
            <li>
            <a href="#transpose">Task 4: Transpose</a>
            </li>
            <li>
            <a href="#eqsys">Task 5: Solving linear equation systems</a>
            </li>
            <li>
            <a href="#matmul">Task 6: Implementing matrix multiplication</a>
            </li>
            <li>
            <a href="#extra">Task 7: Extra exercises</a>
            </li>
        </ul>
    </div>
</article>

The cell below defines matrices `A`
, `B`
, `C`
, `D`
, `E`
 that are used throughout the exercise:


In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Define matrices to be used in the tasks:
A = np.array([
    [1, 0.5, 1/3, 0.25],
    [0.5, 1/3, 0.25, 0.2],
    [1/3, 0.25, 0.2, 1/6],
    [0.25, 0.2, 1/6, 1/7]
])

B = np.array([
    [-16, 15, -14, 13],
    [-12, 11, -10, 9],
    [-8, 7, -6, 5],
    [-4, 3, -2, 1]
])

C = np.array([
    [1, 1/2, 1/3, 1/4],
    [1/2, 1/3, 1/4, 1/5],
    [1/3, 1/5, 1/7, 1/9],
    [1/4, 1/7, 1/8, 1/9],
])

D = np.array([
    [2, 4, 5/2],
    [-3/4, 2, 0.25],
    [0.25, 0.5, 2]
])

E = np.array([
    [1, -0.5, 3/4],
    [3/2, 0.5, -2],
    [0.25, 1, 0.5]
])

D_inv = np.linalg.inv(D)
E_inv = np.linalg.inv(E)


---
**Task 1 (easy): Inverses👩‍💻**
1. Use [`np.linalg.inv`
](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)
 to calculate  the inverse of $A$ and $C$.
2. Verify that $AA^{-1}=I$ and $CC^{-1}=I$. If the results differ from your expectations, argue why this is the case. 


**Hint**
The question relates to the limitations of floating point numbers.


---

In [4]:
# Write your solution here
print(np.linalg.inv(A))
print(A @ np.linalg.inv(A)) # differs slightly - most likely due to floating point precision
print("\n", np.linalg.inv(C))
print(C @ np.linalg.inv(C)) # differs slightly - most likely due to floating point precision

[[   16.  -120.   240.  -140.]
 [ -120.  1200. -2700.  1680.]
 [  240. -2700.  6480. -4200.]
 [ -140.  1680. -4200.  2800.]]
[[ 1.00000000e+00  1.13686838e-13  0.00000000e+00  0.00000000e+00]
 [-1.42108547e-14  1.00000000e+00 -2.27373675e-13  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]

 [[   -72.   -225.    525.     42.]
 [  1260.   3675.  -8820.   -630.]
 [ -3696. -10710.  25830.   1764.]
 [  2700.   7830. -18900.  -1260.]]
[[ 1.00000000e+00  0.00000000e+00 -1.81898940e-12  1.13686838e-13]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -4.54747351e-13  1.00000000e+00]]


## Properties

---
**Task 2 (easy): Inverse properties👩‍💻**
Use the code cell below to verify that:
1. $D^{-1}E^{-1} = (ED)^{-1}$
2. $D^{-1}E^{-1} \neq (DE)^{-1}$


---

In [ ]:
# Write your solution here
print(D_inv @ E_inv, "\n\n", np.linalg.inv(E @ D)) # Almost equal - minor variations due to floating point precision
print("\n\n\n", D_inv @ E_inv, "\n\n", np.linalg.inv(D @ E)) # Quite different values

[[ 0.25261376  0.13578836 -0.51301587]
 [-0.08601058  0.11462434  0.18539683]
 [ 0.16592593 -0.18962963  0.17777778]] 

 [[ 0.25261376  0.13578836 -0.51301587]
 [-0.08601058  0.11462434  0.18539683]
 [ 0.16592593 -0.18962963  0.17777778]]



 [[ 0.25261376  0.13578836 -0.51301587]
 [-0.08601058  0.11462434  0.18539683]
 [ 0.16592593 -0.18962963  0.17777778]] 

 [[ 0.21096296 -0.256      -0.1517037 ]
 [-0.15365079  0.20571429  0.56634921]
 [ 0.05367196 -0.28342857  0.12833862]]



---
**Task 3 (easy): The determinant👩‍💻**
1. Calculate the determinant of $A$, $B$, and $C$ using [`np.linalg.det`
](https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html<elem-4>.linalg.det)
.
2. Determine which of the matrices $A,B,C$ have an inverse.
3. Calculate the inverses of the matrices using [`np.linalg.inv`
](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html<elem-7>.linalg.inv)
. Explain what happens and how this is related to your answer in (2).


---

In [21]:
from numpy.linalg import LinAlgError
# Write your solution here
print("Determinant of A: ", np.linalg.det(A)) # non-zero determinant == has inverse
print("Determinant of B: ", np.linalg.det(B)) # zero determinant == no inverse
print("Determinant of C: ", np.linalg.det(C)) # non-zero determinant == has inverse

print("\nInverse of A: \n", np.linalg.inv(A)) # non-zero determinant == has inverse
try:
    print("Inverse of B: \n", np.linalg.inv(B)) # zero determinant == no inverse
except LinAlgError:
    print("Inverse of B failed with LinAlgError")
print("Inverse of C: \n", np.linalg.inv(C)) # non-zero determinant == has inverse

Determinant of A:  1.6534391534393115e-07
Determinant of B:  0.0
Determinant of C:  1.0498026371041163e-07

Inverse of A: 
 [[   16.  -120.   240.  -140.]
 [ -120.  1200. -2700.  1680.]
 [  240. -2700.  6480. -4200.]
 [ -140.  1680. -4200.  2800.]]
Inverse of B failed with LinAlgError
Inverse of C: 
 [[   -72.   -225.    525.     42.]
 [  1260.   3675.  -8820.   -630.]
 [ -3696. -10710.  25830.   1764.]
 [  2700.   7830. -18900.  -1260.]]



---
**Task 4 (easy): Transpose👩‍💻**
1. Verify that $(D^{-1})^\top$ and ${D^\top}^{-1}$ are equal.


**Hint**
The transpose of a matrix `A`
 in Numpy can be calculated with `A.T`
.


---

In [22]:
# Write your solution here
print(np.linalg.inv(D).T)
print(np.linalg.inv(D.T))

[[ 0.32804233  0.13227513 -0.07407407]
 [-0.57142857  0.28571429  0.        ]
 [-0.33862434 -0.2010582   0.59259259]]
[[ 0.32804233  0.13227513 -0.07407407]
 [-0.57142857  0.28571429 -0.        ]
 [-0.33862434 -0.2010582   0.59259259]]


## Linear equations
Matrices can represent systems of linear equations

$$
Ax=b
$$
where $A$ is the coefficient matrix, $x$ the vector of unknowns, and $b$ is the vector of the dependent variables.
A solution can be found using

$$
\begin{align*}
A^{-1}Ax&=A^{-1}b\\
x &= A^{-1}b.
\end{align*}
$$

---
**Task 5 (medium): Solving linear equation systems👩‍💻**
For each of the following sets of linear equations determine whether a unique solution exits. Recall that the determinant 
can be used to determine whether a matrix has an inverse. Your answers have to be submitted in [Grasple](https://app.grasple.com/#/courses/10532/ci/733997/diagnoses/12886)
:
a)

$$ 
\begin{align*}
2x + 3y  &= -1\\
x + y  &= 0\\
\end{align*}
$$
b)

$$
\begin{align*}
1x + 0y  &= 5\\
0x + 1y  &= 7\\
\end{align*}
$$
c)

$$
\begin{align*}
0x + y  &= -1\\
-2x + -3y  &= 2\\
\end{align*}
$$
d)

$$
\begin{align*}
x + -3y + 3z &= 0.5\\
x - 5y + 3z& = 0.5\\
6z + -6y + 4x &= 1.
\end{align*}
$$
e)

$$
\begin{align*}
2x + 3y + 4z &= 2\\
x + 4z + y &= -2\\
4z + 5y + 2x &= 3.
\end{align*}
$$
f)

$$
\begin{align*}
x + y + z &= 2\\
2x + 2z + 2y &= -2\\
3z + 3y + 3x &= 3.
\end{align*}
$$

---

In [25]:
# Write your solutions here
print("Determinant of A for (a): ", np.linalg.det(np.array([[2, 1], [3, 1]]).T))
print("Determinant of A for (b): ", np.linalg.det(np.array([[1, 0], [0, 1]]).T))
print("Determinant of A for (c): ", np.linalg.det(np.array([[0, -2], [1, -3]]).T))
print("Determinant of A for (d): ", np.linalg.det(np.array([[1, 1, 4], [-3, -5, -6], [3, 3, 6]]).T))
print("Determinant of A for (e): ", np.linalg.det(np.array([[2, 1, 2], [3, 1, 5], [4, 4, 4]]).T))
print("Determinant of A for (f): ", np.linalg.det(np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]]).T))

Determinant of A for (a):  -1.0
Determinant of A for (b):  1.0
Determinant of A for (c):  2.0
Determinant of A for (d):  12.000000000000005
Determinant of A for (e):  -7.999999999999998
Determinant of A for (f):  0.0


## Matrix multiplication (optional)
For an $N\times D$ matrix $A$ and a $D\times K$ matrix $B$, the 
matrix multiplication (or matrix product) is an $N\times K$ matrix $R$. Elements $R_{ij}$ of $R$ can be calculated 
using the following formula

$$
R_{ij} = \sum_{d=1}^D A_{id}B_{dj}.
$$
In other words, it is the dot product of the $i$'th row vector of $A$ and the $j$'th column vector of $B$.

---
**Task 6 (medium): Implementing matrix multiplication👩‍💻**
Implement matrix multiplication in the `matmul`
 function in the code cell below. You may use either Python lists or Numpy arrays, but the intention is to not use Numpy's functions for matrix multiplication (i.e., `np.dot`
, `@`
, `np.matmul`
, etc.). You may, however, use `np.dot`
 for the purpose of computing the inner product between row and column vectors.

**Hint**
It might be helpful to calculate the correct result by hand first, to make debugging easier.


---

In [39]:
def matmul(a, b):
    N = len(a)
    D = len(a[0])
    assert D == len(b)
    K = len(b[0])

    R = np.zeros((N, K))
    for i in range(N):
        for j in range(K):
            R[i, j] = sum([ai * bj for ai, bj in zip(a[i], [bk[j] for bk in b])])
    return R
    

ma = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [1, 1, 1]
]

mb = [
    [5, 4, 9, 1],
    [2, 1, 7, 1],
    [8, 0, 1, 1]
]

print(matmul(ma, mb))
print(np.matmul(ma, mb))

[[ 33.   6.  26.   6.]
 [ 78.  21.  77.  15.]
 [123.  36. 128.  24.]
 [ 15.   5.  17.   3.]]
[[ 33   6  26   6]
 [ 78  21  77  15]
 [123  36 128  24]
 [ 15   5  17   3]]



---
**Task 7 (easy): Extra exercises💡**
Additional exercises are available on Grasple. Complete these if you need more practice with fundamental linear algebra operations and properties:
1. [Matrix Operations](https://app.grasple.com/#/courses/10532/ci/694300/subjects/3936)

2. [Addition, Scalar Multiplication and Transposition](https://app.grasple.com/#/courses/10532/ci/694301/subjects/3935)

3. [Inverse Matrices](https://app.grasple.com/#/courses/10532/ci/735682/subjects/3939)



---